jenkins:
  systemMessage: "Jenkins configured automatically using Jenkins Configuration as Code"
  numExecutors: 4
  scmCheckoutRetryCount: 3
  mode: NORMAL
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "${JENKINS_ADMIN_PASSWORD}"
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"
          - name: "developer"
            permissions:
              - "Overall/Read"
              - "Job/Build"
              - "Job/Read"
            assignments:
              - "developer"

tool:
  git:
    installations:
      - name: "Default"
        home: "git"
  maven:
    installations:
      - name: "Maven 3.9.6"
        home: "/usr/share/maven"
  nodejs:
    installations:
      - name: "NodeJS 18"
        home: "/usr/local/nodejs"
  docker:
    installations:
      - name: "Docker"
        home: "/usr/bin/docker"

unclassified:
  location:
    url: "http://localhost:8080"
  timestamper:
    allPipelines: true
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize

jobs:
  - script: >
      pipelineJob('example-pipeline') {
        definition {
          cps {
            script('''
              pipeline {
                agent any
                environment {
                  DOCKER_REGISTRY = 'your-registry.com'
                  DOCKER_IMAGE = 'example-app'
                }
                stages {
                  stage('Checkout') {
                    steps {
                      checkout scm
                    }
                  }
                  stage('Build') {
                    steps {
                      sh 'mvn clean package'
                    }
                  }
                  stage('Test') {
                    steps {
                      sh 'mvn test'
                    }
                  }
                  stage('Build Docker') {
                    steps {
                      sh 'docker build -t ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${BUILD_NUMBER} .'
                    }
                  }
                }
                post {
                  always {
                    cleanWs()
                  }
                }
              }
            ''')
          }
        }
      }

plugins:
  required:
    - name: "configuration-as-code"
      version: "1.59"
    - name: "git"
      version: "4.15.0"
    - name: "pipeline-model-definition"
      version: "1.9.3"
    - name: "docker-workflow"
      version: "1.28"
    - name: "maven-plugin"
      version: "3.19"
    - name: "nodejs"
      version: "1.5.1"
    - name: "role-strategy"
      version: "3.1.1"
    - name: "timestamper"
      version: "1.18"
    - name: "workflow-aggregator"
      version: "2.6" 